[[people]]
name = "胡书丽"
avatar = ""
research_interests = []
bio = ""
homepage = "https://scholar.google.com/citations?user=8oFXgxQAAAAJ&hl=en&oi=ao"

[[people]]
name = "殷明浩"
avatar = ""
research_interests = []
bio = ""
homepage = "https://scholar.google.com/citations?hl=en&user=QAeUfiIAAAAJ"
