[[news]]
date = "2026-05-13"
content = "我顺利完成了硕士论文答辩，正式成为一名硕士。😆"

[[news]]
date = "2026-05-04"
content = "我们在大规模图上加权全支配集问题的大邻域搜索工作被 **KBS** 接收。🥳"

[[news]]
date = "2026-05-01"
content = "我们在基数约束与 SAT 问题上的局部搜索工作被 **IJCAI 2026** 接收。🥳"

[[news]]
date = "2024-06-22"
content = "我刚刚从东北师范大学毕业，被评为优秀毕业生。"

[[news]]
date = "2023-09-22"
content = "我将开始在东北师范大学攻读计算机科学硕士学位。"

[[news]]
date = "2023-06-01"
content = "我前往中国科学院计算技术研究所作为访问学生。"

[[news]]
date = "2022-03-07"
content = "我开始建立博客来记录我的想法和生活。"
