"""Pinned FontTools production font builder/verifier. No content or Vault access."""
from pathlib import Path
import hashlib
import json
import sys
from collections import defaultdict
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[2]
SOURCES = json.loads((ROOT / 'scripts/fonts/sources.json').read_text())

def digest(data):
    return hashlib.sha256(data).hexdigest()

def ranges(chars):
    result = []
    for char in sorted(chars):
        if result and char == result[-1][1] + 1:
            result[-1][1] = char
        else:
            result.append([char, char])
    return ','.join(f'U+{a:X}' if a == b else f'U+{a:X}-{b:X}' for a, b in result)

def source_font(source):
    path = ROOT / 'assets/fonts' / source['file']
    assert digest(path.read_bytes()) == source['sha256'], 'Source checksum mismatch'
    font = TTFont(path, recalcTimestamp=False)
    assert 'fvar' not in font and font['OS/2'].usWeightClass == source['weight']
    return font

def build(out, fingerprint):
    requested = set(map(ord, (out / 'ui.txt').read_text()))
    manifest = {'fingerprint': fingerprint, 'strategy': 'UI last-face priority; dense 256-codepoint blocks and packed sparse spans', 'fonts': []}
    css = ['/* Generated by scripts/fonts/subset-ui-font.ts. Do not edit. */']
    for source in SOURCES:
        original = source_font(source)
        cmap = set(original.getBestCmap())
        info = {**source, 'sourceCodepoints': len(cmap), 'sourceVersion': original['name'].getDebugName(5), 'files': []}
        groups = defaultdict(set)
        for char in cmap:
            groups[char // 256].add(char)
        # Full source coverage first, exact UI range last. Same-family matching
        # prefers the last face, avoiding fallback-shard requests for UI glyphs.
        # Pack sparse Unicode blocks instead of producing hundreds of tiny files
        # with repeated name/license/layout tables. Dense blocks declared later
        # take priority where a sparse span crosses them; UI remains last.
        sparse = sorted(c for chars in groups.values() if len(chars) < 32 for c in chars)
        plans = []
        for index in range(0, len(sparse), 256):
            chars = set(sparse[index:index+256])
            plans.append((f'sparse-{index//256}', chars, f'U+{min(chars):X}-{max(chars):X}', False))
        plans += [(f'{block:x}', chars, f'U+{block*256:X}-{block*256+255:X}', False) for block, chars in sorted(groups.items()) if len(chars) >= 32]
        plans.append(('ui', requested & cmap, ranges(requested & cmap), True))
        for label, chars, unicode_range, ui in plans:
            if not chars:
                continue
            font = source_font(source)
            options = subset.Options()
            options.hinting = False
            options.drop_tables += ['FFTM']  # legacy timestamp metadata, not shaping
            options.layout_features = ['*']
            options.name_IDs = ['*']
            options.name_legacy = True
            options.name_languages = ['*']
            sub = subset.Subsetter(options=options)
            sub.populate(unicodes=chars)
            sub.subset(font)
            names = {1: source['family'], 2: source['style'], 3: f"{source['id']}-{label}",
                     4: f"{source['family']} {source['style']}", 6: f"{source['id']}-{source['style']}-{label}",
                     16: source['family'], 17: source['style']}
            for record in font['name'].names:
                if record.nameID in names:
                    record.string = names[record.nameID].encode(record.getEncoding())
            for name_id, value in names.items():
                font['name'].setName(value, name_id, 3, 1, 0x409)
            if 'CFF ' in font:
                font['CFF '].cff.fontNames = [names[6]]
                top = font['CFF '].cff.topDictIndex[0]
                top.FamilyName, top.FullName = names[1], names[4]
            font.flavor = 'woff2'
            temporary = out / 'font.woff2'
            font.save(temporary)
            data = temporary.read_bytes()
            sha = digest(data)
            # Immutable generation directory for dev/concurrent writers; Vite
            # supplies the production content hash. Avoid hashing twice in CSS.
            name = f"{fingerprint[:16]}/{source['id']}-{label}.woff2"
            (out / name).parent.mkdir(parents=True, exist_ok=True)
            temporary.rename(out / name)
            # Check encoded output, not only the requested input set.
            actual = TTFont(out / name).getBestCmap()
            assert set(actual) == chars, f'Encoded cmap mismatch: {name}'
            info['files'].append({'file': name, 'sha256': sha, 'bytes': len(data), 'ui': ui, 'codepoints': sorted(chars), 'unicodeRange': unicode_range})
            css.append(f'@font-face{{font-family:"{source["family"]}";src:url("./{name}") format("woff2");font-style:normal;font-weight:{source["weight"]};font-display:swap;unicode-range:{unicode_range};}}')
        assert set().union(*(set(f['codepoints']) for f in info['files'])) == cmap
        manifest['fonts'].append(info)
    text = '\n'.join(css) + '\n'
    (out / 'fonts.css').write_text(text)
    manifest['cssSha256'] = digest(text.encode())
    (out / 'manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, separators=(',', ':')) + '\n')
    verify(out)

def verify(out):
    manifest = json.loads((out / 'manifest.json').read_text())
    css = (out / 'fonts.css').read_bytes()
    assert digest(css) == manifest['cssSha256']
    total = ui_total = 0
    for info, source in zip(manifest['fonts'], SOURCES, strict=True):
        union = set()
        for item in info['files']:
            data = (out / item['file']).read_bytes()
            assert digest(data) == item['sha256'] and len(data) == item['bytes']
            font = TTFont(out / item['file'])
            assert set(font.getBestCmap()) == set(item['codepoints'])
            assert font['OS/2'].usWeightClass == source['weight'] and 'fvar' not in font
            assert font['name'].getDebugName(1) == source['family']
            union.update(font.getBestCmap())
            total += len(data)
            if item['ui']:
                ui_total += len(data)
        assert union == set(source_font(source).getBestCmap()), 'Full source coverage must be conserved'
        selected = {}
        for item in info['files']:
            for interval in item['unicodeRange'].split(','):
                ends = interval.removeprefix('U+').split('-')
                for char in range(int(ends[0], 16), int(ends[-1], 16) + 1):
                    if char in union:
                        selected[char] = item
        assert all(char in selected[char]['codepoints'] for char in union), 'Last matching CSS face must actually contain the glyph'
        if source['id'] == 'notes-cjk':
            ui = next(f for f in info['files'] if f['ui'])
            assert set(map(ord, '旅途还在继续')) <= set(ui['codepoints'])
        print(f"[fonts] {source['id']}: {len(union)} codepoints, {len(info['files'])} files, weight {source['weight']}")
    print(f'[fonts] UI {ui_total} B; all generated fonts {total} B (not a page download)')

if __name__ == '__main__':
    if sys.argv[1] == 'build':
        build(Path(sys.argv[2]), sys.argv[3])
    elif sys.argv[1] == 'verify':
        verify(Path(sys.argv[2]))
    else:
        raise SystemExit('Expected build or verify')
