[[people]]
name = "Shuli Hu"
avatar = ""
research_interests = []
bio = ""
homepage = "https://scholar.google.com/citations?user=8oFXgxQAAAAJ&hl=en&oi=ao"

[[people]]
name = "Minghao Yin"
avatar = ""
research_interests = []
bio = ""
homepage = "https://scholar.google.com/citations?hl=en&user=QAeUfiIAAAAJ"
