[[news]]
date = "May 13, 2026"
content = "I have completed my Master's Thesis Defense, now I become a Master. 😆"

[[news]]
date = "May 4, 2026"
content = "Our paper on large neighborhood search for weighted total dominating set problem on massive graphs was accepted by **KBS**. 🥳"

[[news]]
date = "May 1, 2026"
content = "Our paper on using local search for SAT with cardinality constraints was accepted by **IJCAI 2026**. 🥳"

[[news]]
date = "June 22, 2024"
content = "I just graduated from Northeast Normal University as an outstanding graduate student."

[[news]]
date = "Sept. 22, 2023"
content = "I will start pursuing a master degree in Computer Science at Northeast Normal University."

[[news]]
date = "June 1, 2023"
content = "I went to Institute of Computing Technology, Chinese Academy of Sciences as a visiting student."

[[news]]
date = "Mar. 7, 2022"
content = "I started to build blog to record my thoughts and LIFE"
